# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_likes', '0003_auto_20170919_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='book',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='liked_users',
            field=models.ManyToManyField(null=True, related_name='liked_books', to='books_likes.User'),
        ),
        migrations.DeleteModel(
            name='likes',
        ),
    ]
